package ch.bbw.siegrist.hotel.persitance.entity;
// Generated 05.07.2016 18:51:09 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mahnung generated by hbm2java
 */
public class Mahnung  implements java.io.Serializable {


     private int mahnungId;
     private Date mahndatum;
     private int rechnungIdfs;

    public Mahnung() {
    }

    public Mahnung(int mahnungId, Date mahndatum, int rechnungIdfs) {
       this.mahnungId = mahnungId;
       this.mahndatum = mahndatum;
       this.rechnungIdfs = rechnungIdfs;
    }
   
    public int getMahnungId() {
        return this.mahnungId;
    }
    
    public void setMahnungId(int mahnungId) {
        this.mahnungId = mahnungId;
    }
    public Date getMahndatum() {
        return this.mahndatum;
    }
    
    public void setMahndatum(Date mahndatum) {
        this.mahndatum = mahndatum;
    }
    public int getRechnungIdfs() {
        return this.rechnungIdfs;
    }
    
    public void setRechnungIdfs(int rechnungIdfs) {
        this.rechnungIdfs = rechnungIdfs;
    }




}


