package ch.bbw.siegrist.hotel.persitance.entity;
// Generated 05.07.2016 18:51:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Position generated by hbm2java
 */
public class Position  implements java.io.Serializable {


     private Integer positionId;
     private Benutzer benutzer;
     private Buchung buchung;
     private Leistung leistung;
     private Integer anzahl;
     private BigDecimal preis;
     private Date datum;

    public Position() {
    }

    public Position(Benutzer benutzer, Buchung buchung, Leistung leistung, Integer anzahl, BigDecimal preis, Date datum) {
       this.benutzer = benutzer;
       this.buchung = buchung;
       this.leistung = leistung;
       this.anzahl = anzahl;
       this.preis = preis;
       this.datum = datum;
    }
   
    public Integer getPositionId() {
        return this.positionId;
    }
    
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
    public Benutzer getBenutzer() {
        return this.benutzer;
    }
    
    public void setBenutzer(Benutzer benutzer) {
        this.benutzer = benutzer;
    }
    public Buchung getBuchung() {
        return this.buchung;
    }
    
    public void setBuchung(Buchung buchung) {
        this.buchung = buchung;
    }
    public Leistung getLeistung() {
        return this.leistung;
    }
    
    public void setLeistung(Leistung leistung) {
        this.leistung = leistung;
    }
    public Integer getAnzahl() {
        return this.anzahl;
    }
    
    public void setAnzahl(Integer anzahl) {
        this.anzahl = anzahl;
    }
    public BigDecimal getPreis() {
        return this.preis;
    }
    
    public void setPreis(BigDecimal preis) {
        this.preis = preis;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


