package ch.bbw.siegrist.hotel.persitance.entity;
// Generated 23.05.2016 16:48:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Zahlung generated by hbm2java
 */
public class Zahlung  implements java.io.Serializable {


     private int zahlungId;
     private int buchungIdfs;
     private BigDecimal betrag;
     private Date zahldatum;

    public Zahlung() {
    }

    public Zahlung(int zahlungId, int buchungIdfs, BigDecimal betrag, Date zahldatum) {
       this.zahlungId = zahlungId;
       this.buchungIdfs = buchungIdfs;
       this.betrag = betrag;
       this.zahldatum = zahldatum;
    }
   
    public int getZahlungId() {
        return this.zahlungId;
    }
    
    public void setZahlungId(int zahlungId) {
        this.zahlungId = zahlungId;
    }
    public int getBuchungIdfs() {
        return this.buchungIdfs;
    }
    
    public void setBuchungIdfs(int buchungIdfs) {
        this.buchungIdfs = buchungIdfs;
    }
    public BigDecimal getBetrag() {
        return this.betrag;
    }
    
    public void setBetrag(BigDecimal betrag) {
        this.betrag = betrag;
    }
    public Date getZahldatum() {
        return this.zahldatum;
    }
    
    public void setZahldatum(Date zahldatum) {
        this.zahldatum = zahldatum;
    }




}


